"use client";
// import type { Metadata } from "next";
import { usePathname } from "next/navigation";
import "./globals.css";
// import { useEffect } from "react";
// import ReactGA from "react-ga";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { pathDescriptions } from "@/utils";

// ReactGA.initialize("G-YESDGWM45W");

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathName = usePathname();
  const description = pathDescriptions[pathName] || "Nexios Technologies LLP";

  const appTitle = pathName
    .substring(1)
    .replace(/-/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());

  // useEffect(() => {
  //   ReactGA.pageview(pathName + window.location.search);
  // }, [pathName]);

  return (
    <html lang="en">
      <head>
        <title>{`${
          pathName === "/"
            ? "Nexios-Mobile & Web development"
            : `${appTitle} - Nexios Technologies`
        }`}</title>
        <meta name="description" content={description} />
        <meta
          name="google-site-verification"
          content="2RotKNz-4bf_xmgnkcyTQgZoNy-_g5TL6-pfXo_vBgI"
        />
        <meta name="robots" content="noindex,nofollow" />
        <link rel="icon" href="/icon.png" sizes="32*32" />
        {/* <Script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-YESDGWM45W"
        ></Script>
        <Script id="google-analytics">
          {`
            window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', 'G-YESDGWM45W');
            `}
        </Script> */}
      </head>
      <body>
        {!pathName.includes("/admin") && <Header />}
        <div className="">{children}</div>
        {!pathName.includes("/admin") && <Footer />}
      </body>
    </html>
  );
}
